"""create products packages and groups tables

Revision ID: 1f310a7f8051
Revises:
Create Date: 2026-04-05 00:30:23.874503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f310a7f8051"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("group_code", sa.Integer(), nullable=False),
        sa.Column("name_uz", sa.String(), nullable=True),
        sa.Column("name_ru", sa.String(), nullable=True),
        sa.Column("name_lat", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("group_code"),
    )
    op.create_table(
        "products",
        sa.Column("mxik", sa.String(), nullable=False),
        sa.Column("mxik_name_uz", sa.String(), nullable=True),
        sa.Column("mxik_name_ru", sa.String(), nullable=True),
        sa.Column("mxik_name_lat", sa.String(), nullable=True),
        sa.Column("label_for_check", sa.Integer(), nullable=True),
        sa.Column("international_code", sa.String(), nullable=True),
        sa.Column("use_package", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("update_at", sa.BigInteger(), nullable=True),
        sa.Column("label", sa.Integer(), nullable=True),
        sa.Column("cash_sale", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("mxik"),
    )
    op.create_table(
        "packages",
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("mxik_code", sa.String(), nullable=True),
        sa.Column("name_uz", sa.String(), nullable=True),
        sa.Column("name_ru", sa.String(), nullable=True),
        sa.Column("name_lat", sa.String(), nullable=True),
        sa.Column("package_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["mxik_code"], ["products.mxik"]),
        sa.PrimaryKeyConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("packages")
    op.drop_table("products")
    op.drop_table("groups")
    # ### end Alembic commands ###
